# Importing Required Packages

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

# Import Data

In [3]:
loan_data_backup = pd.read_csv('loan.csv')

C:\Users\Yashveer\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
loan_df = loan_data_backup.copy()

In [5]:
for i, col in enumerate(loan_df.columns):
    print(str(col), end='\t\t\t')
    print(type(loan_df[col][0]), end='\t\t\t')
    print(loan_df[col].isna().sum())

id			<class 'numpy.float64'>			2260668
member_id			<class 'numpy.float64'>			2260668
loan_amnt			<class 'numpy.int64'>			0
funded_amnt			<class 'numpy.int64'>			0
funded_amnt_inv			<class 'numpy.float64'>			0
term			<class 'str'>			0
int_rate			<class 'numpy.float64'>			0
installment			<class 'numpy.float64'>			0
grade			<class 'str'>			0
sub_grade			<class 'str'>			0
emp_title			<class 'str'>			166969
emp_length			<class 'str'>			146907
home_ownership			<class 'str'>			0
annual_inc			<class 'numpy.float64'>			4
verification_status			<class 'str'>			0
issue_d			<class 'str'>			0
loan_status			<class 'str'>			0
pymnt_plan			<class 'str'>			0
url			<class 'numpy.float64'>			2260668
desc			<class 'float'>			2134601
purpose			<class 'str'>			0
title			<class 'str'>			23325
zip_code			<class 'str'>			1
addr_state			<class 'str'>			0
dti			<class 'numpy.float64'>			1711
delinq_2yrs			<class 'numpy.float64'>			29
earliest_cr_line			<class 'str'>			29
inq_last_6mths			<class 'numpy.float64'>		

## Preprocessing

### term

In [6]:
loan_df['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [7]:
loan_df['term'] = loan_df['term'].str.replace(' 36 months', '36')
loan_df['term'] = loan_df['term'].str.replace(' 60 months', '60')

loan_df['term'] = pd.to_numeric(loan_df['term'])
loan_df['term'].unique()

array([36, 60], dtype=int64)

### emp_length

In [8]:
loan_df['emp_length'].unique()

array(['10+ years', '6 years', '4 years', '< 1 year', '2 years',
       '9 years', nan, '5 years', '3 years', '7 years', '1 year',
       '8 years'], dtype=object)

In [9]:
loan_df['emp_length'] = loan_df['emp_length'].str.replace('10+ years', '10', regex = False)
loan_df['emp_length'] = loan_df['emp_length'].str.replace('6 years', '6')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('4 years', '4')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('< 1 year', '0')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('2 years', '2')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('9 years', '9')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('5 years', '5')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('3 years', '3')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('7 years', '7')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('1 year', '1')
loan_df['emp_length'] = loan_df['emp_length'].str.replace('8 years', '8')

In [10]:
loan_df['emp_length'] = pd.to_numeric(loan_df['emp_length'])
loan_df['emp_length'].unique()

array([10.,  6.,  4.,  0.,  2.,  9., nan,  5.,  3.,  7.,  1.,  8.])

### issue_d

In [11]:
loan_df['issue_d'].unique()

array(['Dec-2018', 'Nov-2018', 'Oct-2018', 'Sep-2018', 'Aug-2018',
       'Jul-2018', 'Jun-2018', 'May-2018', 'Apr-2018', 'Mar-2018',
       'Feb-2018', 'Jan-2018', 'Sep-2016', 'Aug-2016', 'Jul-2016',
       'Jun-2016', 'May-2016', 'Apr-2016', 'Mar-2016', 'Feb-2016',
       'Jan-2016', 'Dec-2016', 'Nov-2016', 'Oct-2016', 'Dec-2015',
       'Nov-2015', 'Oct-2015', 'Sep-2015', 'Aug-2015', 'Jul-2015',
       'Jun-2015', 'May-2015', 'Apr-2015', 'Mar-2015', 'Feb-2015',
       'Jan-2015', 'Mar-2017', 'Feb-2017', 'Jan-2017', 'Sep-2017',
       'Aug-2017', 'Jul-2017', 'Jun-2017', 'May-2017', 'Apr-2017',
       'Dec-2013', 'Nov-2013', 'Oct-2013', 'Sep-2013', 'Aug-2013',
       'Jul-2013', 'Jun-2013', 'May-2013', 'Apr-2013', 'Mar-2013',
       'Feb-2013', 'Jan-2013', 'Dec-2012', 'Nov-2012', 'Oct-2012',
       'Sep-2012', 'Aug-2012', 'Jul-2012', 'Jun-2012', 'May-2012',
       'Apr-2012', 'Mar-2012', 'Feb-2012', 'Jan-2012', 'Dec-2014',
       'Nov-2014', 'Oct-2014', 'Sep-2014', 'Aug-2014', 'Jul-20

In [12]:
loan_df['issue_d'] = pd.to_datetime(loan_df['issue_d'], format = "%b-%Y")
loan_df['issue_d'].unique()

array(['2018-12-01T00:00:00.000000000', '2018-11-01T00:00:00.000000000',
       '2018-10-01T00:00:00.000000000', '2018-09-01T00:00:00.000000000',
       '2018-08-01T00:00:00.000000000', '2018-07-01T00:00:00.000000000',
       '2018-06-01T00:00:00.000000000', '2018-05-01T00:00:00.000000000',
       '2018-04-01T00:00:00.000000000', '2018-03-01T00:00:00.000000000',
       '2018-02-01T00:00:00.000000000', '2018-01-01T00:00:00.000000000',
       '2016-09-01T00:00:00.000000000', '2016-08-01T00:00:00.000000000',
       '2016-07-01T00:00:00.000000000', '2016-06-01T00:00:00.000000000',
       '2016-05-01T00:00:00.000000000', '2016-04-01T00:00:00.000000000',
       '2016-03-01T00:00:00.000000000', '2016-02-01T00:00:00.000000000',
       '2016-01-01T00:00:00.000000000', '2016-12-01T00:00:00.000000000',
       '2016-11-01T00:00:00.000000000', '2016-10-01T00:00:00.000000000',
       '2015-12-01T00:00:00.000000000', '2015-11-01T00:00:00.000000000',
       '2015-10-01T00:00:00.000000000', '2015-09-01

In [13]:
# reference date 2020-01-01
mths_issue_d = list()
for date in loan_df['issue_d']:
    year = date.year
    month = date.month
    
    mths_issue_d.append(((2020-year)*12) + (1 - month))
loan_df['mths_issue_d'] = mths_issue_d

In [14]:
loan_df['mths_issue_d'].unique()

array([ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  37,  38,  39,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  34,  35,  36,
        28,  29,  30,  31,  32,  33,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151,  25,  26,  27], dtype=int64)

### earliest_cr_line

In [15]:
loan_df['earliest_cr_line'].isna().sum()

29

In [16]:
loan_df['earliest_cr_line'].unique()

array(['Apr-2001', 'Jun-1987', 'Apr-2011', 'Feb-2006', 'Dec-2000',
       'Sep-2002', 'Nov-2004', 'Nov-1997', 'Aug-1998', 'Apr-2002',
       'May-2007', 'Dec-2003', 'Jun-2003', 'Oct-2008', 'Jul-1990',
       'Dec-1988', 'Dec-2002', 'Oct-2010', 'Jul-2005', 'Feb-2001',
       'Dec-2004', 'Oct-2001', 'Sep-2003', 'Oct-2004', 'Sep-2010',
       'Oct-1999', 'Feb-1997', 'Jan-1995', 'Aug-2005', 'Apr-2005',
       'Oct-2005', 'Nov-2006', 'Sep-1999', 'Sep-2006', 'Aug-1996',
       'May-2015', 'Nov-1999', 'Dec-1998', 'Aug-1989', 'Apr-2012',
       'Sep-2012', 'Jan-2011', 'Jul-2013', 'Sep-2011', 'Aug-1999',
       'Dec-1991', 'Nov-2007', 'Oct-2007', 'Jul-1986', 'Nov-2014',
       'Apr-1995', 'Jul-1992', 'Aug-2006', 'Oct-1988', 'Feb-2005',
       'Aug-2002', 'Oct-2003', 'Apr-2004', 'Jun-2007', 'Aug-1990',
       'Dec-1990', 'Jul-1997', 'Sep-1988', 'Sep-2008', 'Feb-1999',
       'Apr-2007', 'Aug-2004', 'Dec-2006', 'Mar-2007', 'Oct-2006',
       'Jul-2014', 'May-2005', 'Jun-1995', 'Mar-2014', 'Feb-20

In [17]:
loan_df['earliest_cr_line'] = pd.to_datetime(loan_df['earliest_cr_line'], format = "%b-%Y")
loan_df['earliest_cr_line'].unique()

array(['2001-04-01T00:00:00.000000000', '1987-06-01T00:00:00.000000000',
       '2011-04-01T00:00:00.000000000', '2006-02-01T00:00:00.000000000',
       '2000-12-01T00:00:00.000000000', '2002-09-01T00:00:00.000000000',
       '2004-11-01T00:00:00.000000000', '1997-11-01T00:00:00.000000000',
       '1998-08-01T00:00:00.000000000', '2002-04-01T00:00:00.000000000',
       '2007-05-01T00:00:00.000000000', '2003-12-01T00:00:00.000000000',
       '2003-06-01T00:00:00.000000000', '2008-10-01T00:00:00.000000000',
       '1990-07-01T00:00:00.000000000', '1988-12-01T00:00:00.000000000',
       '2002-12-01T00:00:00.000000000', '2010-10-01T00:00:00.000000000',
       '2005-07-01T00:00:00.000000000', '2001-02-01T00:00:00.000000000',
       '2004-12-01T00:00:00.000000000', '2001-10-01T00:00:00.000000000',
       '2003-09-01T00:00:00.000000000', '2004-10-01T00:00:00.000000000',
       '2010-09-01T00:00:00.000000000', '1999-10-01T00:00:00.000000000',
       '1997-02-01T00:00:00.000000000', '1995-01-01

In [18]:
# reference date 2020-01-01
mths_earliest_cr_line = list()
for date in loan_df['earliest_cr_line']:
    year = date.year
    month = date.month
    
    mths_earliest_cr_line.append(((2020-year)*12) + (1 - month))
loan_df['mths_earliest_cr_line'] = mths_earliest_cr_line

In [19]:
loan_df['mths_earliest_cr_line'].unique()

array([ 225.,  391.,  105.,  167.,  229.,  208.,  182.,  266.,  257.,
        213.,  152.,  193.,  199.,  135.,  354.,  373.,  205.,  111.,
        174.,  227.,  181.,  219.,  196.,  183.,  112.,  243.,  275.,
        300.,  173.,  177.,  171.,  158.,  244.,  160.,  281.,   56.,
        242.,  253.,  365.,   93.,   88.,  108.,   78.,  100.,  245.,
        337.,  146.,  147.,  402.,   62.,  297.,  330.,  161.,  375.,
        179.,  209.,  195.,  189.,  151.,  353.,  349.,  270.,  376.,
        136.,  251.,  153.,  185.,  157.,  154.,  159.,   66.,  176.,
        295.,   70.,  203.,  149.,  282.,  348.,  137.,  145.,  268.,
        240.,  180.,  155.,  169.,   96.,  265.,  130.,  369.,  163.,
         72.,  127.,  536.,   69.,  279.,  250.,  301.,  144.,  246.,
         71.,  231.,  113.,  322.,  128.,  317.,  260.,  256.,  101.,
        422.,  237.,  201.,  200.,  287.,  288.,  178.,  221.,   99.,
        550.,  150.,  263.,  168.,  166.,  197.,  188.,   74.,  132.,
        216.,  424.,

### Filling Missing Values

In [20]:
loan_df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term',
       'mths_issue_d', 'mths_earliest_cr_line'],
      dtype='object', length=147)

In [21]:
# print(loan_df['emp_length'].unique())
# 'verification_status_joint' in loan_df.columns
'initial_list_status' in loan_df.columns

True

In [22]:
loan_df['annual_inc'].fillna(loan_df['annual_inc'].mean(), inplace=True)
loan_df['delinq_2yrs'].fillna(0, inplace=True)
loan_df['inq_last_6mths'].fillna(0, inplace=True)
loan_df['open_acc'].fillna(0, inplace=True)
loan_df['pub_rec'].fillna(0, inplace=True)
loan_df['total_acc'].fillna(0, inplace=True)
loan_df['total_rev_hi_lim'].fillna(0, inplace=True)
loan_df['emp_length'].fillna(0, inplace=True)
loan_df['mths_earliest_cr_line'].fillna(0, inplace=True)

### Splitting Columns

In [25]:
# for col in loan_df.columns:
#     filename = str(col) + '.csv'
#     pd.DataFrame(loan_df[col]).to_csv(filename)

### Get Dummies

In [26]:
categorical_df = loan_df[['grade', 'sub_grade', 'home_ownership', 
                          'verification_status_joint', 'loan_status', 
                          'purpose', 'addr_state', 'initial_list_status']]
prefix_dict = {'grade': 'grade:', 'sub_grade': 'sub_grade:', 'home_ownership': 'home_ownership:', 
                'verification_status_joint': 'verification_status_joint:', 'loan_status': 'loan_status:', 
                'purpose': 'purpose:', 'addr_state': 'addr_state:', 'initial_list_status': 'initial_list_status:'}
dummies_df = pd.get_dummies(categorical_df, prefix=prefix_dict)
# dummies_df

In [27]:
dummies_df.columns

Index(['grade:_A', 'grade:_B', 'grade:_C', 'grade:_D', 'grade:_E', 'grade:_F',
       'grade:_G', 'sub_grade:_A1', 'sub_grade:_A2', 'sub_grade:_A3',
       ...
       'addr_state:_TX', 'addr_state:_UT', 'addr_state:_VA', 'addr_state:_VT',
       'addr_state:_WA', 'addr_state:_WI', 'addr_state:_WV', 'addr_state:_WY',
       'initial_list_status:_f', 'initial_list_status:_w'],
      dtype='object', length=127)

In [71]:
# loan_df.to_csv('loan_df.csv')

In [28]:
categorical_df.to_csv('categorical_df.csv', index = False)

In [29]:
loan_df.to_csv('loan_df.csv', index = False)